### PR TITLE
Platform independence

### PR DESCRIPTION
**Pull request by mpalmsten**
I made a few changes to the toolbox to so that the code is platform independent and users should not have to hard code changes to get the code running.

### CODE REVIEW

**Comment by mpalmsten** [comment]
I checked with people in my office. No one under 50 knew what CR means.

**Comment by jstanleyx** [comment]
My keyboard has neither CR nor <enter>, it has "<-". Or "<--".

**Comment by RobHolman** [comment]
I�m thinking of an appropriate reply.  Give me a day or two.

Rob Holman
SECNAV/CNO Chair in Oceanography

104 Ocean Admin Bldg.
CEOAS-OSU
Corvallis, Oregon, USA 97331-5503
ph: 1-541-737-2914
holman@coas.oregonstate.edu
http://cil-www.coas.oregonstate.edu

**Comment by SRHarrison** [comment]
haha! Actually I did know what <CR> meant. _Carriage return_ - like the typewriters did.

**Pull request merged**
